import type { Metadata } from "next";
import "./globals.css";

import { Syne } from "next/font/google";

const syne = Syne({
  subsets: ["latin"],
  weight: ["400"], // ensure correct weight
  display: "swap",
});


export const metadata: Metadata = {
  title: "NEXUS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${syne.className}`}>

        {children}
      </body>
    </html>
  );
}
